import fs from 'node:fs/promises';import http from 'node:http';import os from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';import {chromium} from 'playwright';
const root=fileURLToPath(new URL('../../../',import.meta.url)),started=Date.now(),report={startedAt:new Date().toISOString(),scenario:'unlock → live waveform → confirmed journal → dense budget → mute/save → reload/resume → disposal',errors:[],checks:[]};let server,browser;
const assert=(b,m)=>{if(!b)throw Error(m);};
async function verifySkipped(page,label){const result=await page.evaluate(async label=>{const {PresentationEventQueue}=await import('/dist/presentation-events.js'),player=audioExample.player;let journal;const before=player.snapshot().played;journal=new PresentationEventQueue({retentionTicks:1,maxPending:8,adapters:{sfx:player.createAdapter({onEnded:event=>journal.finish(event)})}});for(let tick=0;tick<5;tick++){journal.emit({tick,sequence:0,entityId:'skip-'+label,generation:0,kind:'sfx',payload:{soundId:'hit'},policy:'confirmed'});journal.confirmThrough(tick);await Promise.resolve();}journal.confirmThrough(8);journal.collect();const result={label,size:journal.size,active:journal.active.size,processed:journal.stats.started,actualPlayed:player.snapshot().played-before};journal.dispose();return result;},label);assert(result.size===0&&result.active===0&&result.actualPlayed===0,'Skipped confirmed retained: '+label);return result;}
try{
 server=http.createServer(async(req,res)=>{try{const pathname=new URL(req.url,'http://localhost').pathname;if(pathname==='/favicon.ico'){res.writeHead(204).end();return;}const file=path.resolve(root,'.'+pathname);if(!file.startsWith(path.resolve(root)+path.sep))throw Error('path');res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':'text/html; charset=utf-8');res.end(await fs.readFile(file));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})});report.browser=await browser.version();const page=await browser.newPage();page.on('pageerror',e=>report.errors.push(String(e)));await page.goto('http://127.0.0.1:'+server.address().port+'/modules/audio/examples/index.html');await page.waitForFunction(()=>window.audioExample);assert((await page.evaluate(()=>audioExample.player.snapshot())).state==='locked','Context allocated before gesture');
 report.skippedLocked=await verifySkipped(page,'locked');report.offline=await page.evaluate(async()=>{const {audioDefaults,makeNoise,createMix,renderSound}=await import('/dist/audio.js');const rows=[];
  for(const dense of [false,true]){const context=new OfflineAudioContext(1,48000,48000),mix=createMix(context,context.destination),buffer=makeNoise(context),clip=context.createBuffer(1,4800,48000);for(let i=0;i<4800;i++)clip.getChannelData(0)[i]=Math.sin(i*2*Math.PI*440/48000)*.2;
   const tone={category:'sfx',layers:[{kind:'tone',hz:180,end:50,ms:220,gain:.22,type:'sine'},{kind:'noise',hz:2200,ms:90,gain:.14}]},sample={category:'sfx',layers:[{kind:'buffer',bufferId:'clip',ms:100,gain:.2}]};let ended=0;
   for(let i=0;i<(dense?12:1);i++)renderSound(context,mix.input,tone,buffer,{at:i*.003,scale:.8,onEnded:()=>ended++});renderSound(context,mix.input,sample,buffer,{at:.3,buffers:new Map([['clip',clip]]),onEnded:()=>ended++});const rendered=await context.startRendering();await new Promise(r=>setTimeout(r,20));const values=rendered.getChannelData(0);let peak=0,sum=0,finite=true;for(const v of values){finite&&=Number.isFinite(v);peak=Math.max(peak,Math.abs(v));sum+=v*v;}rows.push({dense,peak,rms:Math.sqrt(sum/values.length),finite,ended,expectedEnded:dense?13:2});}return rows;});
 for(const r of report.offline)assert(r.finite&&r.peak>0&&r.peak<.9&&r.rms>0&&r.ended===r.expectedEnded,'Offline output/end cleanup');report.checks.push('Offline real tone/noise/registered AudioBuffer, finite samples and dense peak');
 await page.locator('#tap').click();await page.waitForTimeout(30);report.live=await page.evaluate(async()=>{let peak=0,rms=0;for(let i=0;i<120;i++){const m=audioExample.player.meter();peak=Math.max(peak,m.peak);rms=Math.max(rms,m.rms);await new Promise(r=>setTimeout(r,5));}return {peak,rms,currentTime:audioExample.player.context.currentTime,baseLatency:audioExample.player.context.baseLatency,outputLatency:audioExample.player.context.outputLatency,state:audioExample.player.snapshot()};});assert(report.live.state.state==='running'&&report.live.peak>1e-5,'Live graph stayed silent');await page.waitForTimeout(300);assert((await page.evaluate(()=>audioExample.player.snapshot())).voices===0,'Natural ended leaked voice');report.checks.push('Actual gesture unlock and nonzero live analyser; natural ended cleanup');
 const before=await page.evaluate(()=>audioExample.player.snapshot().played);await page.locator('#confirmed').click();await page.waitForTimeout(400);report.journal=await page.evaluate(()=>({audio:audioExample.player.snapshot(),stats:audioExample.journal.stats,active:audioExample.journal.active.size}));assert(report.journal.audio.played===before+1&&report.journal.stats.duplicates===1&&report.journal.active===0,'Confirmed SFX replayed/retained');report.checks.push('Existing confirmed journal adapter: duplicate one-shot not replayed; natural finish');
 await page.locator('#dense').click();report.dense=await page.evaluate(()=>audioExample.player.snapshot());report.skippedBudget=await verifySkipped(page,'budget');assert(report.dense.voices<=4&&report.dense.maxObserved<=4&&report.dense.dropped>0&&report.dense.bySound.warning>=1,'Budget/priority failed');await page.waitForTimeout(450);assert((await page.evaluate(()=>audioExample.player.snapshot())).voices===0,'Dense voices retained');report.checks.push('Category/global voice budget, drops and higher-priority admission');
 await page.locator('#mute').click();await page.locator('#tap').click();await page.waitForTimeout(100);report.muted=await page.evaluate(()=>({state:audioExample.player.snapshot(),meter:audioExample.player.meter()}));report.skippedMuted=await verifySkipped(page,'muted');assert(report.muted.state.muted&&report.muted.meter.peak<1e-7,'Mute output not silent');await page.locator('#volume').focus();await page.keyboard.press('Home');for(let i=0;i<33;i++)await page.keyboard.press('ArrowRight');await page.reload();await page.waitForFunction(()=>window.audioExample);report.restored=await page.evaluate(()=>audioExample.player.snapshot());assert(report.restored.muted&&Math.abs(report.restored.volume-.33)<1e-9&&report.restored.state==='locked','Volume/mute not restored or context created on reload');report.checks.push('Mute is measured silent; master controls persist; reload stays locked');
 await page.locator('#mute').click();await page.locator('#tap').click();await page.waitForTimeout(50);await page.evaluate(()=>audioExample.player.context.suspend());await page.waitForTimeout(30);report.suspended=await page.evaluate(()=>audioExample.player.snapshot());assert(report.suspended.state==='suspended'&&report.suspended.voices===0,'Suspension retained voices');await page.locator('#tap').click();await page.waitForFunction(()=>audioExample.player.snapshot().state==='running'&&audioExample.player.snapshot().played>=2,null,{timeout:5000});report.resumed=await page.evaluate(async()=>{let peak=0,rms=0;for(let i=0;i<120;i++){const m=audioExample.player.meter();peak=Math.max(peak,m.peak);rms=Math.max(rms,m.rms);await new Promise(r=>setTimeout(r,5));}return {state:audioExample.player.snapshot(),meter:{peak,rms}};});assert(report.resumed.state.state==='running'&&report.resumed.meter.peak>1e-5,'Gesture resume silent');report.checks.push('Actual AudioContext suspend clears voices; next gesture resumes same context without stale playback');
 await page.locator('#confirmed').click();await page.evaluate(async()=>{audioExample.journal.dispose();await audioExample.player.dispose();await audioExample.player.dispose();});report.disposed=await page.evaluate(()=>audioExample.player.snapshot());assert(report.disposed.state==='disposed'&&report.disposed.voices===0,'Dispose failed');assert(!report.errors.length,'JS exceptions');report.result='PASS';report.limits=['Waveform/analyser results verify generated graph output, not speakers or subjective punch.','Suspend was an actual AudioContext API lifecycle exercise; iOS/Android hardware interruption and document-background behavior were not repeated.','No CPU benchmark or long listening test.'];
}catch(error){report.result='FAIL';report.failure=String(error.stack||error);}
finally{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));report.elapsedMs=Date.now()-started;const output=process.env.AUDIO_REPORT_PATH||path.join(os.tmpdir(),'gamekit-audio-'+started+'.json');await fs.writeFile(output,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,reportPath:output}));process.exitCode=report.result==='PASS'?0:1;}
